# 配置数据源相关 使用HikariCP数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sixin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没有可用的连接则发生SQLException，默认30秒
      connection-timeout: 30000
      # 最小连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 200
      # 自动提交
      auto-commit: true
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），默认10分钟
      idle-timeout: 600000
      # 连接池名字
      pool-name: DatebookHikariCP
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认30分钟
      max-lifetime: 28740000
      connection-test-query: SELECT 1

# 配置API端口号
server:
  port: 5928
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
  address: 0.0.0.0

# mybatis配置
mybatis:
  type-aliases-package: com.siyi.pojo
  mapper-locations: classpath:mapper/*.xml

# 通用mapper配置
mapper:
  not-empty: false
  identity: MYSQL

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: countSql

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 80
    height: 80
  tracker-list:            #TrackerList参数,支持多个
    # - 172.31.243.159:22122
    # 请输入你的FastDFStracker服务地址
